package com.farmeazy.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

/**
 * CROP DTO (Data Transfer Object)
 * 
 * PURPOSE: Transfers crop data between client and server for crop management operations.
 * Validates crop information before creating/updating crop records.
 * 
 * KEY FEATURES:
 * 1. Crop Details: name, season, variety, area, expected yield
 * 2. Timeline: sowing date and expected harvest date
 * 3. Status Tracking: current state (PLANTED, GROWING, HARVESTING, HARVESTED)
 * 4. Farm Association: crop belongs to specific farm
 * 5. Notes: Additional information about crop growth
 * 
 * HOW IT WORKS:
 * - Client sends crop creation/update request with farm and crop details
 * - Spring validates required fields (cropName, season, dates, farmId)
 * - Server verifies user owns the farm before creating crop
 * - Crop is created with "PLANTED" status by default
 * - Returned response includes all crop details including ID
 * 
 * VALIDATION RULES:
 * - cropName: Required, non-blank
 * - season: Required, non-blank
 * - sowingDate: Required, not null
 * - expectedHarvestDate: Required, not null
 * - farmId: Required, not null (must be user's farm)
 * - variety, plantingArea, expectedYield, notes: Optional
 * 
 * CROP STATUSES:
 * - PLANTED: Seeds just sown
 * - GROWING: Active growth phase
 * - HARVESTING: Currently being harvested
 * - HARVESTED: Harvest complete, crop cycle ended
 * 
 * USAGE EXAMPLE:
 * POST /api/crops
 * {
 *     "cropName": "Wheat",
 *     "season": "Rabi",
 *     "sowingDate": "2023-10-15",
 *     "expectedHarvestDate": "2024-03-15",
 *     "variety": "HD3086",
 *     "plantingArea": 8.5,
 *     "expectedYield": 4250,
 *     "notes": "Using new irrigation drip system",
 *     "farmId": 1
 * }
 */
public class CropDto {
    
    /**
     * CROP ID - UNIQUE CROP IDENTIFIER
     * Only in responses, generated by database
     * Example: 1, 2, 3
     */
    private Long id;
    
    /**
     * CROP NAME - TYPE OF CROP
     * @NotBlank: Required, cannot be empty
     * Name of the crop being grown
     * Used for identification and recommendations
     * Example: "Wheat", "Rice", "Cotton", "Sugarcane", "Tomato"
     */
    @NotBlank(message = "Crop name is required")
    private String cropName;
    
    /**
     * SEASON - PLANTING SEASON
     * @NotBlank: Required, cannot be empty
     * Season during which crop is planted
     * Important for crop rotation and planning
     * Example: "Kharif" (monsoon), "Rabi" (winter), "Summer"
     */
    @NotBlank(message = "Season is required")
    private String season;
    
    /**
     * SOWING DATE - PLANTING DATE
     * @NotNull: Required, cannot be null
     * Date when seeds were/will be sown
     * Used to calculate crop age and maturity date
     * Format: YYYY-MM-DD (e.g., "2023-10-15")
     */
    @NotNull(message = "Sowing date is required")
    private LocalDate sowingDate;
    
    /**
     * EXPECTED HARVEST DATE - ESTIMATED MATURITY DATE
     * @NotNull: Required, cannot be null
     * Projected date when crop will be ready to harvest
     * Depends on crop type, variety, and growing conditions
     * Format: YYYY-MM-DD (e.g., "2024-03-15")
     */
    @NotNull(message = "Expected harvest date is required")
    private LocalDate expectedHarvestDate;
    
    /**
     * CROP VARIETY - SPECIFIC CULTIVAR
     * Optional field
     * Specific variety/breed within crop type
     * Example: "HD3086" (wheat variety), "Basmati" (rice variety)
     */
    private String variety;
    
    /**
     * PLANTING AREA - SIZE OF CROP FIELD
     * Optional field
     * Area allocated to this crop in hectares
     * Must be ≤ total farm area
     * Example: 8.5, 15.0, 25.75
     */
    private Double plantingArea;
    
    /**
     * EXPECTED YIELD - PROJECTED HARVEST QUANTITY
     * Optional field
     * Expected production in kilograms (kg)
     * Used for yield forecasting and planning
     * Example: 4250, 8500, 12000
     */
    private Integer expectedYield;
    
    /**
     * CROP NOTES - ADDITIONAL INFORMATION
     * Optional field
     * Free-form text for specific details about crop
     * Example: "Using drip irrigation", "Observed leaf spot disease"
     */
    private String notes;
    
    /**
     * STATUS - CURRENT CROP LIFECYCLE STATE
     * Optional field
     * Defaults to "PLANTED" when created
     * Possible values: PLANTED, GROWING, HARVESTING, HARVESTED
     * Used to track where crop is in growing cycle
     * Example: "GROWING"
     */
    private String status;
    
    /**
     * FARM ID - WHICH FARM THIS CROP BELONGS TO
     * @NotNull: Required, cannot be null
     * References the farm where crop is planted
     * User must own this farm (security check)
     * Example: 1
     */
    @NotNull(message = "Farm ID is required")
    private Long farmId;
    
    /**
     * FARM USER ID - FARM OWNER'S ID
     * Set by server from authenticated user
     * Not provided by client
     * Used for user isolation and security
     * Example: 1
     */
    private Long farmUserId;
    
    public CropDto() {}
    
    public CropDto(Long id, String cropName, String season, LocalDate sowingDate, LocalDate expectedHarvestDate, String variety, Double plantingArea, Integer expectedYield, String notes, String status, Long farmId) {
        this.id = id;
        this.cropName = cropName;
        this.season = season;
        this.sowingDate = sowingDate;
        this.expectedHarvestDate = expectedHarvestDate;
        this.variety = variety;
        this.plantingArea = plantingArea;
        this.expectedYield = expectedYield;
        this.notes = notes;
        this.status = status;
        this.farmId = farmId;
    }
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getCropName() { return cropName; }
    public void setCropName(String cropName) { this.cropName = cropName; }
    public String getSeason() { return season; }
    public void setSeason(String season) { this.season = season; }
    public LocalDate getSowingDate() { return sowingDate; }
    public void setSowingDate(LocalDate sowingDate) { this.sowingDate = sowingDate; }
    public LocalDate getExpectedHarvestDate() { return expectedHarvestDate; }
    public void setExpectedHarvestDate(LocalDate expectedHarvestDate) { this.expectedHarvestDate = expectedHarvestDate; }
    public String getVariety() { return variety; }
    public void setVariety(String variety) { this.variety = variety; }
    public Double getPlantingArea() { return plantingArea; }
    public void setPlantingArea(Double plantingArea) { this.plantingArea = plantingArea; }
    public Integer getExpectedYield() { return expectedYield; }
    public void setExpectedYield(Integer expectedYield) { this.expectedYield = expectedYield; }
    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public Long getFarmId() { return farmId; }
    public void setFarmId(Long farmId) { this.farmId = farmId; }
    public Long getFarmUserId() { return farmUserId; }
    public void setFarmUserId(Long farmUserId) { this.farmUserId = farmUserId; }
}
