package com.farmeazy.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * FARM DTO (Data Transfer Object)
 * 
 * PURPOSE: Transfers farm data between client and server for Create/Read/Update operations.
 * Validates farm information before persisting to database.
 * 
 * KEY FEATURES:
 * 1. Farm Information: name, location, size, soil type, water source, description
 * 2. Validation: Ensures required fields are provided
 * 3. User Association: Tracks which user owns the farm
 * 4. Data Transfer: Converts JSON requests to Java objects and vice versa
 * 
 * HOW IT WORKS:
 * - Client sends farm creation/update request with JSON body
 * - Spring deserializes JSON to FarmDto and validates annotations
 * - If validation fails, error response with field-level messages
 * - If validation passes, FarmService converts DTO to Farm entity
 * - Farm is saved to database and returned as FarmDto response
 * 
 * VALIDATION RULES:
 * - farmName: Required, non-blank string
 * - location: Required, non-blank string
 * - areaSize: Required, not null (in hectares)
 * - soilType: Optional
 * - waterSource: Optional
 * - description: Optional
 * 
 * USAGE EXAMPLES:
 * 
 * CREATE FARM (POST /api/farms):
 * {
 *     "farmName": "North Fields",
 *     "location": "District Nashik, Maharashtra",
 *     "areaSize": 10.5,
 *     "soilType": "Loamy",
 *     "waterSource": "Borewell",
 *     "description": "Main farm for wheat and sugarcane"
 * }
 * 
 * UPDATE FARM (PUT /api/farms/{farmId}):
 * {
 *     "farmName": "North Fields - Updated",
 *     "location": "District Nashik, Maharashtra",
 *     "areaSize": 12.0,
 *     "soilType": "Clay-Loamy",
 *     "waterSource": "Canal",
 *     "description": "Recently expanded farm"
 * }
 */
public class FarmDto {
    
    /**
     * FARM ID - UNIQUE FARM IDENTIFIER
     * Only populated in responses, not used in request
     * Generated by database during creation
     * Example: 1, 2, 3
     */
    private Long id;
    
    /**
     * FARM NAME - FARM'S DISPLAY NAME
     * @NotBlank: Required, cannot be empty
     * User-friendly name for the farm
     * Used in listings and selection dropdowns
     * Example: "North Fields", "Green Farm Nashik"
     */
    @NotBlank(message = "Farm name is required")
    private String farmName;
    
    /**
     * FARM LOCATION - PHYSICAL LOCATION/ADDRESS
     * @NotBlank: Required, cannot be empty
     * Geographic location of the farm
     * Can be address, district name, or coordinates description
     * Example: "District Nashik, Maharashtra", "Village Chhatral, Gujarat"
     */
    @NotBlank(message = "Location is required")
    private String location;
    
    /**
     * FARM AREA SIZE - TOTAL FARM SIZE
     * @NotNull: Required, cannot be null
     * Area of the farm in hectares (1 hectare ≈ 2.47 acres)
     * Used for yield calculations and resource planning
     * Must be positive number
     * Example: 10.5, 25.0, 100.75
     */
    @NotNull(message = "Area size is required")
    private Double areaSize;
    
    /**
     * SOIL TYPE - FARM SOIL CLASSIFICATION (OPTIONAL)
     * Indicates type of soil on the farm
     * Helps determine crop suitability
     * Examples: "Loamy", "Sandy", "Clay", "Red Soil", "Black Soil"
     */
    private String soilType;
    
    /**
     * WATER SOURCE - PRIMARY IRRIGATION SOURCE (OPTIONAL)
     * Primary water source for irrigation
     * Critical for crop planning and water management
     * Examples: "Borewell", "River", "Canal", "Pond", "Rainwater", "Tube Well"
     */
    private String waterSource;
    
    /**
     * DESCRIPTION - ADDITIONAL FARM INFORMATION (OPTIONAL)
     * Free-form text for additional details
     * Used to store notes, special conditions, or requirements
     * Example: "Main farm with multiple crops, has solar pump"
     */
    private String description;
    
    /**
     * USER ID - OWNER OF THE FARM
     * References the User who owns this farm
     * Used for user isolation and security
     * Set by server from authenticated user, not by client
     * Example: 1
     */
    private Long userId;
    
    public FarmDto() {}
    
    public FarmDto(Long id, String farmName, String location, Double areaSize, String soilType, String waterSource, String description, Long userId) {
        this.id = id;
        this.farmName = farmName;
        this.location = location;
        this.areaSize = areaSize;
        this.soilType = soilType;
        this.waterSource = waterSource;
        this.description = description;
        this.userId = userId;
    }
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getFarmName() { return farmName; }
    public void setFarmName(String farmName) { this.farmName = farmName; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public Double getAreaSize() { return areaSize; }
    public void setAreaSize(Double areaSize) { this.areaSize = areaSize; }
    public String getSoilType() { return soilType; }
    public void setSoilType(String soilType) { this.soilType = soilType; }
    public String getWaterSource() { return waterSource; }
    public void setWaterSource(String waterSource) { this.waterSource = waterSource; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }
}
