package com.farmeazy.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.NotBlank;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * IRRIGATION SCHEDULE DTO (Data Transfer Object)
 * 
 * PURPOSE: Transfers irrigation schedule data for creating and managing irrigation events.
 * Validates irrigation parameters before creating/updating irrigation records.
 * 
 * KEY FEATURES:
 * 1. Schedule Timing: irrigation date, start time, duration
 * 2. Water Management: planned water amount, actual water used, notes
 * 3. Status Tracking: SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED
 * 4. Crop & Farm Association: links to specific crop and farm
 * 5. Execution Details: completion time, actual vs planned water
 * 
 * HOW IT WORKS:
 * - Farmer creates irrigation schedule for a crop
 * - Specifies date, time, duration, and water amount
 * - Schedule status defaults to "SCHEDULED"
 * - As irrigation progresses, status and actual water are updated
 * - Provides record of all irrigation events for analysis
 * 
 * VALIDATION RULES:
 * - irrigationDate: Required, not null
 * - startTime: Required, not null
 * - duration: Required, not null (in minutes)
 * - waterAmount: Required, not null (in liters)
 * - cropId: Required, not null
 * - farmId: Required, not null
 * 
 * STATUS LIFECYCLE:
 * - SCHEDULED: Irrigation planned, waiting to execute
 * - IN_PROGRESS: Irrigation currently running
 * - COMPLETED: Irrigation finished
 * - CANCELLED: Irrigation cancelled before execution
 * 
 * USAGE EXAMPLE:
 * POST /api/irrigations
 * {
 *     "irrigationDate": "2023-10-20",
 *     "startTime": "06:00:00",
 *     "duration": 120,
 *     "waterAmount": 15000.0,
 *     "status": "SCHEDULED",
 *     "notes": "Morning irrigation for wheat field",
 *     "cropId": 1,
 *     "farmId": 1
 * }
 */
public class IrrigationScheduleDto {
    
    /**
     * SCHEDULE ID - UNIQUE IRRIGATION SCHEDULE IDENTIFIER
     * Only in responses, generated by database
     * Example: 1, 2, 3
     */
    private Long id;
    
    /**
     * IRRIGATION DATE - WHEN IRRIGATION WILL OCCUR
     * @NotNull: Required, cannot be null
     * Date scheduled for irrigation
     * Format: YYYY-MM-DD (e.g., "2023-10-20")
     * Used to plan irrigation in advance (can be future or past date during update)
     */
    @NotNull(message = "Irrigation date is required")
    private LocalDate irrigationDate;
    
    /**
     * START TIME - WHAT TIME IRRIGATION BEGINS
     * @NotNull: Required, cannot be null
     * Time of day when irrigation should start
     * Format: HH:MM:SS (e.g., "06:00:00" for 6 AM)
     * Combined with date for exact scheduling
     */
    @NotNull(message = "Start time is required")
    private LocalTime startTime;
    
    /**
     * DURATION - HOW LONG IRRIGATION RUNS
     * @NotNull: Required, cannot be null
     * Duration of irrigation in minutes
     * Example: 120 (2 hours), 90 (1.5 hours)
     * Used to calculate end time and schedule farm activities
     */
    @NotNull(message = "Duration is required")
    private Integer duration;
    
    /**
     * WATER AMOUNT - PLANNED WATER QUANTITY
     * @NotNull: Required, cannot be null
     * Amount of water for this irrigation in liters
     * Based on crop water requirements and soil conditions
     * Example: 15000.0 (15,000 liters), 25000.5
     */
    @NotNull(message = "Water amount is required")
    private Double waterAmount;
    
    /**
     * STATUS - CURRENT STATE OF IRRIGATION
     * Optional field
     * Defaults to "SCHEDULED" when created
     * Possible values:
     *   - SCHEDULED: Waiting to execute
     *   - IN_PROGRESS: Currently running
     *   - COMPLETED: Finished
     *   - CANCELLED: Cancelled before execution
     * Example: "SCHEDULED", "COMPLETED"
     */
    private String status;
    
    /**
     * NOTES - ADDITIONAL INFORMATION
     * Optional field
     * Free-form text for observations or special conditions
     * Example: "Morning irrigation due to high temperature", "Pump pressure low"
     */
    private String notes;
    
    /**
     * ACTUAL WATER USED - REAL WATER CONSUMPTION
     * Optional field
     * Actual water delivered during execution
     * May differ from planned waterAmount
     * Set after irrigation is completed
     * Example: 14800.0 (slightly less than planned 15000.0)
     */
    private Double actualWaterUsed;
    
    /**
     * CROP ID - WHICH CROP THIS IRRIGATION IS FOR
     * @NotNull: Required, cannot be null
     * References the crop being irrigated
     * Crop must belong to specified farm
     * Example: 1
     */
    @NotNull(message = "Crop ID is required")
    private Long cropId;
    
    /**
     * FARM ID - WHICH FARM THIS IRRIGATION BELONGS TO
     * @NotNull: Required, cannot be null
     * References the farm for user isolation
     * User must own this farm (security check)
     * Example: 1
     */
    @NotNull(message = "Farm ID is required")
    private Long farmId;
    
    /**
     * FARM USER ID - FARM OWNER'S ID
     * Set by server from authenticated user
     * Not provided by client
     * Used for user isolation and security verification
     * Example: 1
     */
    private Long farmUserId;
    
    public IrrigationScheduleDto() {}
    
    public IrrigationScheduleDto(Long id, LocalDate irrigationDate, LocalTime startTime, Integer duration, Double waterAmount, String status, String notes, Double actualWaterUsed, Long cropId, Long farmId) {
        this.id = id;
        this.irrigationDate = irrigationDate;
        this.startTime = startTime;
        this.duration = duration;
        this.waterAmount = waterAmount;
        this.status = status;
        this.notes = notes;
        this.actualWaterUsed = actualWaterUsed;
        this.cropId = cropId;
        this.farmId = farmId;
    }
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public LocalDate getIrrigationDate() { return irrigationDate; }
    public void setIrrigationDate(LocalDate irrigationDate) { this.irrigationDate = irrigationDate; }
    public LocalTime getStartTime() { return startTime; }
    public void setStartTime(LocalTime startTime) { this.startTime = startTime; }
    public Integer getDuration() { return duration; }
    public void setDuration(Integer duration) { this.duration = duration; }
    public Double getWaterAmount() { return waterAmount; }
    public void setWaterAmount(Double waterAmount) { this.waterAmount = waterAmount; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }
    public Double getActualWaterUsed() { return actualWaterUsed; }
    public void setActualWaterUsed(Double actualWaterUsed) { this.actualWaterUsed = actualWaterUsed; }
    public Long getCropId() { return cropId; }
    public void setCropId(Long cropId) { this.cropId = cropId; }
    public Long getFarmId() { return farmId; }
    public void setFarmId(Long farmId) { this.farmId = farmId; }
    public Long getFarmUserId() { return farmUserId; }
    public void setFarmUserId(Long farmUserId) { this.farmUserId = farmUserId; }
}
