-- Schema initialization moved to an external, DBA-run script.
-- See: ../sql/production_add_auth_provider_and_profile_completed.sql
-- Purpose: avoid performing runtime ALTER/UPDATE during application startup.
